export enum RoutePaths {
  ABOUT = '/about',
  ACCOUNT = '/account/:dialog?',
  ALL = '*',
  AUTH = '/auth',
  EXTERNAL_STORE = 'https://store.gozle.com.tm',
  EXTERNAL_VIDEO = 'https://v.gozle.com.tm',
  GOZLE_PAY = '/gozle-pay/:dialog?',
  HOME = '/',
  LOGOUT = '/logout',
  OAUTH_V2_AUTH = '/oauth/v2/auth',
  PASSWORD_RESET = '/auth/password-reset',
  PAYMENT = '/payment',
  PRIVACY = '/privacy-policy',
  SECURITY = '/security/:dialog?',
  SUPPORT = '/support',
  TERMS = '/terms-of-use',
  TEST = '/test',
}
